### PR TITLE
feat(fmod): fmod 2.02.06 with aarch64

### PR DESCRIPTION
**Pull request by martinwang2002**
FMOD 2.02.06 supports aarch64
(There is manylinux2014_aarch64 wheel already, but no aarch64 support for fmod)

Unimplemented:
* Darwin

### CODE REVIEW

**Comment by martinwang2002** [comment]
@K0lb3 any idea on how to extract fmod on darwin?

**Comment by K0lb3** [comment]
Thanks for working on this.

The discord user VaDiM found a solution for Mac some time ago.
image
I just forgot about it afterward due to rl.


I guess that you already checked that your changes work and produce good audio and not some weird noise?

**Comment by martinwang2002** [comment]
I just noticed that there are some weird noise. (Sad news.

**Comment by ds5678** [comment]
> some weird noise

I encountered this for AssetRipper when I tried bumping to any FMOD 2.x version. If you find a way around it, I'd be interested to hear.

**Comment by martinwang2002** [comment]
image

I'm now pretty sure that fmod 2.02 is doing something weird.

From typetree, the audio is 44100Hz **16bits**, i.e. we should use FMOD_SOUND_FORMAT_PCM16. For all available formats, see [fmod sound format](https://www.fmod.com/resources/documentation-api?version=2.02&page=core-api-sound.html#fmod_sound_format)

However, the logs of `fmodL` (debug mode of fmod) gives
```
[LOG] SystemI::createSoundInternal             : Create data=0x3c352d00, mode=0x00000800
[LOG] SystemI::createSoundInternal             : exinfo->cbsize             = 24
[LOG] SystemI::createSoundInternal             : exinfo->length             = 15008
[LOG] SystemI::createSoundInternal             : exinfo->numchannels        = 1
[LOG] SystemI::createSoundInternal             : exinfo->defaultfrequency   = 44100
[LOG] SystemI::createSoundInternal             : exinfo->format             = 3
[LOG] SystemI::createSoundInternal             : Sample 0/1: name='(null)', format=5, channels=1, frequency=44100, lengthbytes=14912, lengthpcm=70339, pcmblocksize=0, loopstart=0, loopend=0, mode=0x00000000, channelmask=0x00000000, channelorder=0, peakvolume=0.000000.
```

`format=5` is FMOD_SOUND_FORMAT_PCM32. That's the audio format we get in the output wav and there is a disagreement with the typetree.

`length` is different in the picture and logs since I used different audio files.

Code:
```
exinfo = byref(CREATESOUNDEXINFO(length=clip.m_Size,
                                     numchannels=1,
                                     defaultfrequency=44100,
                                     format=3,
                                     ))
# exinfo = byref(CREATESOUNDEXINFO(length=clip.m_Size))

snd_ptr = c_void_p()
ckresult(_dll.FMOD_System_CreateSound(sys_ptr, bytes(
        clip.m_AudioData), 0x00000800,  exinfo, byref(snd_ptr)))
```

----

Another try is to use FMOD_OPENMEMORY  + FMOD_OPENRAW. For all FMOD_MODES, see [FMOD_MODE](https://www.fmod.com/resources/documentation-api?version=2.02&page=core-api-common.html#fmod_mode)

Code:
```
exinfo = byref(CREATESOUNDEXINFO(length=clip.m_Size,
                                     numchannels=1,
                                     defaultfrequency=44100,
                                     format=3,
                                     ))
# exinfo = byref(CREATESOUNDEXINFO(length=clip.m_Size))

snd_ptr = c_void_p()
ckresult(_dll.FMOD_System_CreateSound(sys_ptr, bytes(
        clip.m_AudioData),  0x00001000 | 0x00000800,  exinfo, byref(snd_ptr)))
```

Now, I can successfully set the audio format to be PCM 16 bits. But, fmod is not returning any audio samples.
```
[LOG] SystemI::createSoundInternal             : Create data=0x5b47930, mode=0x00001800
[LOG] SystemI::createSoundInternal             : exinfo->cbsize             = 24
[LOG] SystemI::createSoundInternal             : exinfo->length             = 15008
[LOG] SystemI::createSoundInternal             : exinfo->numchannels        = 1
[LOG] SystemI::createSoundInternal             : exinfo->defaultfrequency   = 44100
[LOG] SystemI::createSoundInternal             : exinfo->format             = 3
[LOG] SystemI::createSoundInternal             : Sample 0/0: name='(null)', format=3, channels=1, frequency=44100, lengthbytes=15008, lengthpcm=5002, pcmblocksize=0, loopstart=0, loopend=0, mode=0x00000000, channelmask=0x00000000, channelorder=0, peakvolume=0.000000.
```

**Sample 0/0**: No audio file is returned

**Comment by martinwang2002** [comment]
I'm closing this for 
1. AssetStudio uses fmod 1.x. Just stick to that.
2. fmod 2.01 supports unity 2017 and higher and fmod 2.02 supports unity 2019 and higher. Only fmod 2.02 has aarch64 support.

**Pull request closed without merging**
